### ISSUE TITLE
Tests on another repo not passing 

### ISSUE THREAD

**Issue by Conorc1000** [dwyl/hapi-postgres-connection#12]
When we run our tests locally the preAuth event was published before the connection was completed. 
Adding this code in the onPreAuth extension allows the tests to pass. 

``` javascript
if(PG_CON.length === 0) {
      pg.connect(process.env.DATABASE_URL, function(err, client, done) {
        PG_CON.push({ client: client, done: done});
        request.pg = {
          client: PG_CON[0].client,
          done: PG_CON[0].done
        }
        reply.continue();
      });
    } else {
      request.pg = {
        client: PG_CON[0].client,
        done: PG_CON[0].done
      }
      reply.continue();
    }
```

**Comment by nelsonic** [comment]
@Conorc1000 can you please share the link to the snapshot of the code where you were experiencing that issue... I saw it on your computer so I know it happened. but in order to re-produce it I need the git ref/hash so I can see the circumstance that leads to the connection not being made before the `server.ext('onPreAuth'` is fired...

**Comment by nelsonic** [comment]
@Conorc1000 published new version to NPM. please confirm if that fixes your issue. :+1:
