### ISSUE TITLE
Should not be opening a database connection and exposing it?

### ISSUE THREAD

**Issue by samhstn** [dwyl/hapi-postgres-connection#23]
When looking around for good plugin practices I came across [this gist](https://gist.github.com/hueniverse/f01faf422eb038d87d57#when-should-i-not-use-multiple-plugins) which says that opening a database connection in a plugin and exposing it is a bad practice

and this comment: ["using plugins to load a db connection is an odd pattern"](https://github.com/hapijs/discuss/issues/182)

I am quite confused as to the reasoning behind why this is considered a bad practice. I don't see any reason for thinking that exposing your database connection this way should lead to any issues.

I think this module provides a really nice way to initialise your database connection in one place and then be able to cleanly make database queries anywhere in your application so I'm going to still use it.

But why are some people in the hapi community saying that it's bad to be exposing your db connection across your application?

**Comment by eliasmalik** [comment]
@shouston3 

I think in general it's considered bad practice to have dependencies crossing plugin boundaries. Plugins are (ideally) meant to be fully isolated units of functionality. Removing one or more plugins from your app shouldn't break it completely. If there's some app-critical bit of setup you need to do, it should be done outside of a plugin (perhaps just as a node module). 

Out of ignorance, I have consistently broken this 'rule', because I have been using plugins simply as a way to modularise the functionality of my app. I don't think this is really what they were intended for. If you find yourself using `server.dependency` a lot, or having to be careful about the order in which plugins are registered, I would now consider this a code smell.

This is a separate issue to whether or not you should expose a DB connection on `server.app`, which is what (I think) you actually are interested in, and the hapi maintainer seems to agree that this is a good/acceptable pattern, given what he's said on the issue and gist you linked.

**Comment by nelsonic** [comment]
@shouston3 thank you _very_ much for raising this issue/question! 😍 
while I _respect_ that _some_ people might consider putting a DB connection in a plugin to be a "no-no" as far as "Best Practice" is concerned, I haven't (_personally_) seen a _simpler alternative_ which reduces the number of lines of code `require`-ing and "booting" a connection in each route handler and which allows me to _close_ the connection _once_ at the end of my tests (_instead of having to write "_tare down_" code in `each` of my tests...!_) 

This plugin opens the connection to PostgreSQL ***once*** and makes that connection available _anywhere_ in the request lifecycle so the request handler can _conveniently_ make database queries _without_ having to include "_boilerplate connection_" code in every file and without worrying about _closing_ the connection once the query has been executed.

`if` those are our two "_requirements_" I would _absolutely_ ***love*** to hear an alternative way of doing this without using a plugin.  this way seemed like a "win-win" to me... but as always, I'm `hapi` to be shown the `error` of thinking by a more [XP](https://en.wikipedia.org/wiki/Experience_point) person...

I _geniuinely_ don't understand why it's considered "bad" (_probably because I'm not "smart" enough..._), but having read _many_ books on "_patterns_", "_security_" and "_performance_" and not found _anything_ warning me that this is a "_bad idea_", I too am going to `continue` doing it this way until someone can present a convincing argument for an alternative method. 👍 

@eliascodes 🥇 
Crossing plugin boundaries is a "_horrible idea_" for _most_ plugins. (_agree 100%_!)

The apps we have built with PostgreSQL (_or [Redis](https://github.com/dwyl/hapi-redis-connection) for that matter_) simply _don't **work**_ when the database connection fails.
And _instantiating_ the DB connection in _each_ plugin/handler feels "**un**[***DRY***](https://en.wikipedia.org/wiki/Don't_repeat_yourself)" to _me_... 

If we _prefer_ to expose the DB connection on `server.app` we could _add_ that to this plugin.
However I tend to find that having the DB available on `request` works for _most_ cases. 

> I'm _definitely_ not an "_Expert_" on Hapi or Plugins, so if other more _experienced_ people have some _wisdom_ to share on this topic, I'd _love_ to learn...! 
e.g: @mtharrison who _literally_ wrote [**the book on `Hapi`**](https://www.amazon.com/d/cka/Hapi-js-Action-Mr-Matt-Harrison/1633430219) might have some _insight_...? ❤️
