### ISSUE TITLE
 PG.connect is deprecated

### ISSUE THREAD

**Issue by Kuchiriel** [dwyl/hapi-postgres-connection#27]
it won't normally happen, only if I use babel targeting node 3

When I try to start my server, I see this.

(node:3834) DeprecationWarning: PG.connect is deprecated - please see the upgrade guide at https://node-postgres.com/guides/upgrading

**Comment by nelsonic** [comment]
@Kuchiriel thanks for reporting this! 
@naazy do you have time to investigate/update?

**Comment by Kuchiriel** [comment]
Guys, I'm sorry, it won't normally happen, only if I use babel targeting node 3. I forgot to inform this.

**Comment by nelsonic** [comment]
@Kuchiriel thanks for the additional info. (_those are useful details, and v. specific_!) 👍 
We still need to upgrade to the latest version in _any_ case because:
![image](https://user-images.githubusercontent.com/194400/28410399-7f7a6a24-6d35-11e7-9f26-41d82a6a6585.png)
https://david-dm.org/dwyl/hapi-postgres-connection
But it's _unlikely_ that we are going to "target" node v.3 as it's no longer supported:
https://github.com/nodejs/LTS#lts-schedule1

**Comment by naazy** [comment]
@Kuchiriel this has now been fixed in version 6.2.0. Please upgrade to hapi-postgres-connection 6.2.0 and close the issue if satisfied that this has been resolved :smile:

**Comment by Kuchiriel** [comment]
@nelsonic @naazy, Thank you very much guys!
